### ISSUE TITLE
Drunken Map doesn't work with LayerSwipe dijit

### ISSUE THREAD

**Issue by nickpeihl** [raykendo/ArcGIS_Map_Enhancements#1]
Hi Ken,

Very clever. However, the drunken map doesn't play well with the Layer Swipe dijit. I suspect you're too wasted to care though. :beers: Cheers!

![drunk-map](https://cloud.githubusercontent.com/assets/1638483/6947068/89f25b9c-d859-11e4-8fe2-149162fd4820.gif)

**Comment by raykendo** [comment]
LOL Good catch.  Will work on that.

**Comment by raykendo** [comment]
With the new version, Layer Swipe control drags as normal, while the map gets around to updating itself, er, eventually. Good enough?

**Comment by nickpeihl** [comment]
Hi Ken,

Much better. My alcoholic clients will be pleased. :100:
